import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Created by PamelaPeixinho on 26/03/17.
 */
public class SimpleForm {

	private JTextField searchField;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
		searchField = new JTextField();
		searchField.setBackground(new Color(-10722974));
		panel1.add(searchField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST,
																									 GridConstraints.FILL_HORIZONTAL,
																									 GridConstraints.SIZEPOLICY_WANT_GROW,
																									 GridConstraints.SIZEPOLICY_FIXED, null,
																									 new Dimension(150, -1), null, 0, false));
		final Spacer spacer1 = new Spacer();
		panel1.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
																							 GridConstraints.FILL_VERTICAL, 1,
																							 GridConstraints.SIZEPOLICY_WANT_GROW, null, null,
																							 null, 0, false));
	}
}
